name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o docker.sh "https://get.docker.com"
         curl -o pve_source.tar.gz "https://bbs.x86pi.cn/file/topic/2023-11-28/file/01ac88d7d2b840cb88c15cb5e19d4305b2.gz"
         curl -o xiaoya.sh "https://raw.githubusercontent.com/monlor/docker-xiaoya/main/install.sh"
         curl -o uninstall.sh "https://raw.githubusercontent.com/monlor/docker-xiaoya/main/uninstall.sh"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          docker.sh
          pve_source.tar.gz
          xiaoya.sh
          uninstall.sh
        tag_name: latest
